/**
 * Integrate gate evidence bundle (PRD §12.2, FR-GATE).
 */

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { readJournalEvents, readJournalTail } from "./journal.mjs";
import { generateBatchPostMortem } from "./postmortem.mjs";
import { reconcileBatch } from "./reconcile.mjs";

const TASKPLANE_CONFIG_PATH = ".pi/taskplane-config.json";

/**
 * @param {string} projectRoot
 * @param {string} batchId
 */
export function evidenceDir(projectRoot, batchId) {
	return path.join(projectRoot, ".spine", "runtime", batchId, "evidence");
}

/**
 * @param {string} projectRoot
 */
function readTaskplaneTestingCommands(projectRoot) {
	const configPath = path.join(projectRoot, TASKPLANE_CONFIG_PATH);
	if (!fs.existsSync(configPath)) return null;

	try {
		const parsed = JSON.parse(fs.readFileSync(configPath, "utf-8"));
		return parsed?.taskRunner?.testing?.commands ?? null;
	} catch {
		return null;
	}
}

/**
 * @param {import("../../bin/spine-config.mjs").SpineConfig|null} config
 * @param {string} projectRoot
 */
export function resolveTestingCommands(config, projectRoot) {
	const spineTesting = config?.testing ?? {};
	const taskplane = readTaskplaneTestingCommands(projectRoot) ?? {};

	return {
		test:
			(typeof spineTesting.test === "string" && spineTesting.test.trim()) ||
			(typeof taskplane.unit === "string" && taskplane.unit.trim()) ||
			(typeof taskplane.test === "string" && taskplane.test.trim()) ||
			"",
		build:
			(typeof spineTesting.build === "string" && spineTesting.build.trim()) ||
			(typeof taskplane.build === "string" && taskplane.build.trim()) ||
			"",
		testWithCoverage:
			(typeof spineTesting.testWithCoverage === "string" && spineTesting.testWithCoverage.trim()) ||
			(typeof taskplane.testWithCoverage === "string" && taskplane.testWithCoverage.trim()) ||
			"",
	};
}

/**
 * @param {string} projectRoot
 * @param {string} command
 * @param {number} [maxBytes]
 */
function runEvidenceCommand(projectRoot, command, maxBytes = 256 * 1024) {
	if (!command) return { ok: false, skipped: true, output: "" };

	try {
		const output = execFileSync(command, {
			cwd: projectRoot,
			encoding: "utf-8",
			shell: true,
			stdio: ["ignore", "pipe", "pipe"],
			timeout: 10 * 60 * 1000,
			maxBuffer: maxBytes,
		});
		return { ok: true, skipped: false, output: String(output ?? "") };
	} catch (err) {
		const stdout = err && typeof err === "object" && "stdout" in err ? String(err.stdout ?? "") : "";
		const stderr = err && typeof err === "object" && "stderr" in err ? String(err.stderr ?? "") : "";
		const message = err instanceof Error ? err.message : String(err);
		return {
			ok: false,
			skipped: false,
			output: `${stdout}${stderr}\n[exit] ${message}`.trim(),
		};
	}
}

/**
 * @param {string} projectRoot
 * @param {string} baseBranch
 * @param {string} orchBranch
 */
function collectDiffStat(projectRoot, baseBranch, orchBranch) {
	try {
		return execFileSync("git", ["diff", "--stat", `${baseBranch}..${orchBranch}`], {
			cwd: projectRoot,
			encoding: "utf-8",
			stdio: ["ignore", "pipe", "pipe"],
		}).trim();
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		return `(git diff --stat failed: ${message})`;
	}
}

/**
 * @param {object|null|undefined} batchState
 */
export function buildTaskScorecard(batchState) {
	const tasks = Array.isArray(batchState?.tasks) ? batchState.tasks : [];
	const lines = [
		"# Batch evidence summary",
		"",
		`| Field | Value |`,
		`|-------|-------|`,
		`| Batch ID | ${batchState?.batchId ?? batchState?.id ?? "—"} |`,
		`| Phase | ${batchState?.phase ?? "—"} |`,
		`| Base branch | ${batchState?.baseBranch ?? "—"} |`,
		`| Orch branch | ${batchState?.orchBranch ?? "—"} |`,
		`| Tasks (total) | ${batchState?.totalTasks ?? tasks.length} |`,
		`| Succeeded | ${batchState?.succeededTasks ?? "—"} |`,
		`| Failed | ${batchState?.failedTasks ?? "—"} |`,
		"",
		"## Task scorecard",
		"",
	];

	if (tasks.length === 0) {
		lines.push("_No task rows in batch state._");
	} else {
		lines.push("| Task | Status | Done file |");
		lines.push("|------|--------|-----------|");
		for (const task of tasks) {
			lines.push(
				`| ${task.taskId ?? "—"} | ${task.status ?? "—"} | ${task.doneFileFound ? "yes" : "no"} |`,
			);
		}
	}

	lines.push("", "_Generated by pi-spine integrate gate (TP-021)._");
	return `${lines.join("\n")}\n`;
}

/**
 * @param {object} ctx
 * @param {string} ctx.projectRoot
 * @param {string} ctx.batchId
 * @param {object|null} [ctx.batchState]
 * @param {import("../../bin/spine-config.mjs").SpineConfig|null} [ctx.config]
 */
export function collectEvidenceBundle(ctx) {
	const { projectRoot, batchId, batchState = null, config = null } = ctx;
	const dir = evidenceDir(projectRoot, batchId);
	fs.mkdirSync(dir, { recursive: true });

	/** @type {string[]} */
	const evidenceRefs = [];

	const reconciliation = reconcileBatch({ projectRoot, batchState, verbose: true });
	const journalTail = readJournalTail(readJournalEvents(projectRoot, batchId));
	const summary = generateBatchPostMortem(batchState, journalTail, reconciliation, projectRoot);
	fs.writeFileSync(path.join(dir, "summary.md"), summary, "utf-8");
	evidenceRefs.push("evidence/summary.md");

	const baseBranch = batchState?.baseBranch ?? config?.baseBranch ?? "main";
	const orchBranch = batchState?.orchBranch ?? null;
	if (orchBranch) {
		const diffStat = collectDiffStat(projectRoot, baseBranch, orchBranch);
		fs.writeFileSync(path.join(dir, "diff-stat.txt"), `${diffStat}\n`, "utf-8");
		evidenceRefs.push("evidence/diff-stat.txt");
	}

	const gates = config?.gates ?? {};
	const testing = resolveTestingCommands(config, projectRoot);
	const collectTest = gates.collectTestEvidence !== false;
	const collectBuild = gates.collectBuildEvidence === true;

	if (collectTest && testing.test) {
		const result = runEvidenceCommand(projectRoot, testing.test);
		fs.writeFileSync(path.join(dir, "test-output.txt"), `${result.output}\n`, "utf-8");
		evidenceRefs.push("evidence/test-output.txt");
	}

	if (collectBuild && testing.build) {
		const result = runEvidenceCommand(projectRoot, testing.build);
		fs.writeFileSync(path.join(dir, "build-output.txt"), `${result.output}\n`, "utf-8");
		evidenceRefs.push("evidence/build-output.txt");
	}

	if (testing.testWithCoverage) {
		const result = runEvidenceCommand(projectRoot, testing.testWithCoverage);
		fs.writeFileSync(path.join(dir, "coverage-output.txt"), `${result.output}\n`, "utf-8");
		evidenceRefs.push("evidence/coverage-output.txt");
	}

	for (const ref of collectWorkerOutputEvidenceRefs(projectRoot, batchId)) {
		evidenceRefs.push(ref);
	}

	return { evidenceDir: dir, evidenceRefs };
}

/**
 * @param {string} projectRoot
 * @param {string} batchId
 */
function collectWorkerOutputEvidenceRefs(projectRoot, batchId) {
	const lanesDir = path.join(projectRoot, ".spine", "runtime", batchId, "lanes");
	if (!fs.existsSync(lanesDir)) return [];

	/** @type {string[]} */
	const refs = [];
	for (const laneDir of fs.readdirSync(lanesDir)) {
		if (!laneDir.startsWith("lane-")) continue;
		const lanePath = path.join(lanesDir, laneDir);
		for (const name of fs.readdirSync(lanePath)) {
			if (!name.startsWith("worker-output-") || !name.endsWith(".log")) continue;
			refs.push(path.join(".spine", "runtime", batchId, "lanes", laneDir, name));
		}
	}
	return refs.sort();
}
